spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: com.cobis.cloud.infra.microservice.commons.CobisPhysicalNamingStrategy
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/cobis
    username: admin
    password: C0bis2019
  liquibase:
    change-log: classpath:/db/changelog/changelog-cobis.xml
    liquibase-schema: cobis
    enabled: false
