spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: com.cobis.cloud.infra.microservice.commons.CobisPhysicalNamingStrategy
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-gp-mysql-aurora-cluster-rds-cluster.cluster-cn2sc4zc3b8i.us-east-2.rds.amazonaws.com:3306/cobis
    username: admin
    password: C0bis2019
    hikari:
      maximumPoolSize: 10
      minimumIdle: 0
  liquibase:
    change-log: classpath:/db/changelog/changelog-cobis.xml
    liquibase-schema: cobis
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    health:
      sensitive: false
  health:
    db:
      enabled: true
    defaults:
      enabled: true
