spring:
  main:
    # Se deshabilita exposicion de servicios rest
    web-application-type: none
  autoconfigure:
    # Se deshabilita jpa porque no se esta usando
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration