AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  channels-commons-service

  SAM Template for channels-commons-service Load Config


Parameters:
  ApplicationName:
    Type: String
    Description: "Nombre de la aplicaci贸n"
  ConfigurationName:
    Type: String
    Description: "Nombre de la configuraci贸n del perfil"
  EnvironmentName:
    Type: String
    Description: "Nombre del ambiente"

Resources:
  Application:
    Type: AWS::AppConfig::Application
    Properties:
      Name: !Ref ApplicationName

  Strategy:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:
      Name: !Sub '${ApplicationName}-strategy'
      Description: "Estrategia de despliegue."
      DeploymentDurationInMinutes: 1
      FinalBakeTimeInMinutes: 1
      GrowthFactor: 100
      GrowthType: LINEAR
      ReplicateTo: NONE

  Environment:
    DependsOn: Application
    Type: AWS::AppConfig::Environment
    Properties:
      ApplicationId: !Ref Application
      Name: !Ref EnvironmentName
      Description: "Ambiente para el despliegue de plantilla de AppConfig."

  ConfigurationProfile:
    DependsOn: Application
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      LocationUri: "hosted"
      Name: !Ref ConfigurationName
      ApplicationId: !Ref Application

  Deployment:
    DependsOn:
      - Application
      - Environment
      - Strategy
      - ConfigurationProfile
      - HostedConfigurationVersion
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId: !Ref Application
      EnvironmentId: !Ref Environment
      DeploymentStrategyId: !Ref Strategy
      ConfigurationProfileId: !Ref ConfigurationProfile
      ConfigurationVersion: !Ref HostedConfigurationVersion

  HostedConfigurationVersion:
    DependsOn:
      - Application
      - ConfigurationProfile
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref Application
      ConfigurationProfileId: !Ref ConfigurationProfile
      Description: 'Configuraci贸n de versi贸n local'
      ContentType: 'JSON'
      Content: '
      {
        "parameters": {
          "environmentId": "dev1",
          "environmentIdBase": "dev1",
          "region": "us-east-1",
          "environmentIdBaseFront": "dev1",
          "environmentType": "DEVELOPMENT",
          "awsAccountId": "681989517074",
          "imageBatchSharedAccount": "125277160564.dkr.ecr.us-east-1.amazonaws.com/cobis/util/java-exec-from-s3",
          "officialsUserPoolId": "us-east-1_1U2ky2y82",
          "generalPurposeSubnetsId": "subnet-0a528e7553ffbf3d7,subnet-09b2cdfa6e7049a12",
          "generalPurposeSecurityGroupsIds": "sg-055c4ae27248f64b7",
          "databaseSecretArn": "arn:aws:secretsmanager:us-east-1:681989517074:secret:/dev1/ATM/database/credentials-VmbREQ",
          "extDemandDepositsEndPoint": "https://fodun5giw0.execute-api.us-east-1.amazonaws.com/v1/demand-deposits/executor",
          "extLoansEndPoint": "https://lid4z8vdx6.execute-api.us-east-1.amazonaws.com/v1/loans/executor"
        },
        "stack-outputs": [
          "${BASE_ENVIRONMENT_ID}-BasePlatform",
          "${BASE_ENVIRONMENT_ID}-cobis-core-auth",
          "operations-base"
        ],
        "pipeline": {
          "project": {
            "module": "channels",
            "project-key": "cobis-channels-commons-serverless-service",
            "teams-webhook-url": "https://cobiscorp.webhook.office.com/webhookb2/908ef33d-333c-4e52-9b8d-f99384958437@a5e6fcaa-5535-41e3-8d08-2b6676750a3f/JenkinsCI/427888c932e0453386fb500d568a0e17/38ccebc1-db05-415d-bed6-83938d1a4c7c",
            "backend-repo-url": "https://dev.azure.com/cobiscorp/COB/_git/cobis-channels-commons-backend-aws",
            "backend-branch": "develop"
          },
          "liquibase": {
            "liquibase-s3-bucket": "${CICD_BUCKET}",
            "liquibase-batch-job-queue": "${${BASE_ENVIRONMENT_ID}-BasePlatform:GeneralFargateBatchJobQueueName}",
            "liquibase-batch-job-definition": "${${BASE_ENVIRONMENT_ID}-BasePlatform:LiquibaseFargateBatchJobDefinitionName}",
            "liquibase-db-names": "cobis,cob_channels,cob_channels_his",
            "liquibase-db-log-sufijo": "ChannelsCommons",
            "liquibase-deploy-enable": "true"
          },
          "deploy": {
            "stack-name": "${environmentId}-channels-commons",
            "s3-bucket": "${CICD_BUCKET}",
            "prefix": "${environmentId}",
            "aws-default-region": "${region}",
            "capabilities": "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM",
            "non-confirm-change-set": "true",
            "parameters": [
              {
                "parameterKey": "Module",
                "parameterValue": "ChannelsCommons"
              },
              {
                "parameterKey": "LambdaAuthorizer",
                "parameterValue": "auth-authorization-challenge"
              },
              {
                "parameterKey": "Organization",
                "parameterValue": "Cobiscorp"
              },
              {
                "parameterKey": "Version",
                "parameterValue": "0.1"
              },
              {
                "parameterKey": "TenantId",
                "parameterValue": "t1"
              },
              {
                "parameterKey": "ProcessingType",
                "parameterValue": "ONLINE"
              },
              {
                "parameterKey": "ImageBatchSharedResourcesAccount",
                "parameterValue": "${imageBatchSharedAccount}"
              },
              {
                "parameterKey": "DaysRetention",
                "parameterValue": 3
              },
              {
                "parameterKey": "StageMainVersionName",
                "parameterValue": "v1"
              },
              {
                "parameterKey": "LambdaAliasProduction",
                "parameterValue": "production"
              },
              {
                "parameterKey": "LambdaAliasBeta",
                "parameterValue": "beta"
              },
              {
                "parameterKey": "DBConnectionExpirationTime",
                "parameterValue": 300
              },
              {
                "parameterKey": "DashboardName",
                "parameterValue": "COBIS-CHANNELS-COMMONS"
              },
              {
                "parameterKey": "EnvironmentIdBase",
                "parameterValue": "${environmentIdBase}"
              },
              {
                "parameterKey": "EnvironmentType",
                "parameterValue": "${environmentType}"
              },
              {
                "parameterKey": "EnvironmentId",
                "parameterValue": "${environmentId}"
              },
              {
                "parameterKey": "RegionToDeploy",
                "parameterValue": "${region}"
              },
              {
                "parameterKey": "AwsAccountIdToDeploy",
                "parameterValue": "${awsAccountId}"
              },
              {
                "parameterKey": "UserPoolId",
                "parameterValue": "${officialsUserPoolId}"
              },
              {
                "parameterKey": "ValueApiKey",
                "parameterValue": "${environmentIdBase}-qwertyuioplkjhgfcha9"
              },
              {
                "parameterKey": "KmsKeyId",
                "parameterValue": "9c94c8e0-d8d1-47b3-b534-20c671d56d7d"
              },
              {
                "parameterKey": "SecurityGroupIds",
                "parameterValue": "${generalPurposeSecurityGroupsIds}"
              },
              {
                "parameterKey": "SubnetIds",
                "parameterValue": "${generalPurposeSubnetsId}"
              },
              {
                "parameterKey": "StageName",
                "parameterValue": "v1"
              },
              {
                "parameterKey": "LambdaAliasProduction",
                "parameterValue": "production"
              },
              {
                "parameterKey": "LambdaAliasBeta",
                "parameterValue": "beta"
              },
              {
                "parameterKey": "StageMainVersionName",
                "parameterValue": "v1"
              },
              {
                "parameterKey": "SecretArn",
                "parameterValue": "${databaseSecretArn}"
              },
              {
                "parameterKey": "EnvironmentIdBaseFront",
                "parameterValue": "${environmentIdBaseFront}"
              },
              {
                "parameterKey": "AWSBatchServiceRole",
                "parameterValue": "arn:aws:iam::${awsAccountId}:role/${environmentIdBase}-batch-compute-service-role"
              },
              {
                "parameterKey": "ExtLoansApiKey",
                "parameterValue": "${environmentIdBase}-Kl6YQq9KM43XTGKr60bhZ1ebqYm2ChHe81eQoLHG"
              },
              {
                "parameterKey": "ExtDemandDeposits",
                "parameterValue": "${extDemandDepositsEndPoint}"
              },
              {
                "parameterKey": "ExtLoans",
                "parameterValue": "${extLoansEndPoint}"
              },
              {
                "parameterKey": "ExtDemandDepositsApiKey",
                "parameterValue": "${environmentIdBase}-qwertyuioplkjhgfdsadev1"
              },
              {
                "parameterKey": "EnvironmentIdInternal",
                "parameterValue": "${environmentIdBase}"
              },
              {
                "parameterKey": "LogLevel",
                "parameterValue": "INFO"
              },
              {
                "parameterKey": "DbTarget",
                "parameterValue": "master"
              },
              {
                "parameterKey": "DaysRetentionDev",
                "parameterValue": "1"
              },
              {
                "parameterKey": "TimeZone",
                "parameterValue": "America/Bogota"
              },
              {
                "parameterKey": "DaysRetentionProd",
                "parameterValue": "30"
              },
              {
                "parameterKey": "DaysRetentionQA",
                "parameterValue": "7"
              },
              {
                "parameterKey": "ChannelsCommonsExecutorLambdaConfiguration",
                "parameterValue": "1024:2:0:0:0:0:INFO"
              }
            ]
          }
        }
      }'