parameters:
- name: PROJECT_KEY
  default: 'cobis-atm-serverless-service-aws'
- name: DEPLOY_CONFIG
  default: 'atm-deploy' 

trigger:
 branches:
   include:
     - 'develop'
     - 'quality'
     - 'master'

pool: 'aws-pool-linux' 

resources:
  repositories:
    - repository: templates
      type: git
      name: cobis-cloud-devops
      ref: 'refs/tags/v6.0.0'

stages:
- template: azure/stages/templates/microserviceTemplate.yml@templates
  parameters:
    PROJECT_KEY: '${{ parameters.PROJECT_KEY }}'
    DEPLOY_CONFIG: '${{ parameters.DEPLOY_CONFIG }}'