spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: com.cobis.cloud.infra.microservice.commons.CobisPhysicalNamingStrategy
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bddstg1.core.cloud-cobiscorp.com:3333/cobis
    username: ProductFactorySrv
    password: MaYnBg&5?+
    hikari:
      maximumPoolSize: 10
      minimumIdle: 0
  liquibase:
    change-log: classpath:/db/changelog/changelog-cobis.xml
    liquibase-schema: cobis
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    health:
      sensitive: false
  health:
    db:
      enabled: true
    defaults:
      enabled: true
aws:
  region: us-west-2
  poolId: us-west-2_UfF65Hc8c