server:
  port: 8087
  servlet:
    context-path:
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: com.cobis.cloud.infra.microservice.commons.CobisPhysicalNamingStrategy
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
        format_sql: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/cobis
    username: admin
    password: C0bis2019
    hikari:
      maximumPoolSize: 10
      minimumIdle: 0

  liquibase:
    change-log: classpath:/db/changelog/changelog-cobis.xml
    liquibase-schema: cobis
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    health:
      sensitive: false
  health:
    db:
      enabled: true
    defaults:
      enabled: true

logging:
  level:
    Root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework: DEBUG

aws:
  region: us-east-1
  poolId: us-east-1_1U2ky2y82
  poolIdApp: us-east-1_NnvRNn0jT

cobis:
  restrpc:
    connection-config:
      -
        name: ach
        url: https://iq2flhnuo2.execute-api.us-east-1.amazonaws.com
        path: /v1/ach/executor
        timeout: 15000
        apiKey: dev1-qwertyuioplkjachyla7-exec

      -
        name: accounts
        url: https://owtwqyk00f.execute-api.us-east-1.amazonaws.com
        path: /v1/demand-deposits/executor
        timeout: 15000
        apiKey: dm1-qwertyuioplkjhgfdsadm1

      -
        name: client
        url: https://f1tpxfc0h5.execute-api.us-east-1.amazonaws.com
        path: /v1/customers/executor
        timeout: 15000
        apiKey: qwertyuioplkjhgfdsa2dv-xecu

      -
        name: customers
        url: https://b79qs9po2b.execute-api.us-east-1.amazonaws.com
        path: /v1/customers/executor
        timeout: 15000
        apiKey: dev1-qwertyuioplkjhgfdsa2dv

      -
        name: channels
        url: https://jqdkqsgov5.execute-api.us-east-1.amazonaws.com
        path: /v1/channels-commons/executor
        timeout: 15000
        apiKey: dev1-qwertyuioplkjhgfcha9-exec

integration:
  dda:
    baseURL: https://ddaccounts-api.dev1.product.cobiscloud.com/generic/v1
    baseURLGen: https://ddaccounts-api.dev1.product.cobiscloud.com/transactional/v1
    apiKey: dev1-qwertyuioplkjhgfdsadev1
