spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
        format_sql: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bddservice:3306/cobis
    username: root
    password: my-secret-pw
  liquibase:
    change-log: classpath:/db/changelog/changelog-cobis.xml
    liquibase-schema: cobis
    enabled: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    health:
      sensitive: false
  health:
    db:
      enabled: true
    defaults:
      enabled: true
