AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  channels-commons-service

  SAM Template for channels-commons-service lambda

Parameters:
  ChannelsCommonsAutoScalingRole:
    Type: String
    Description: "ChannelsCommonsAutoScalingRole."
  TimeZone:
    Type: String
    Description: "Identificador de zona horaria."
  LambdaAliasProduction:
    Type: String
    Description: Environment alias
  LambdaAliasBeta:
    Type: String
    Description: Environment alias
  ApiGatewayResponseMessage400:
    Type: String
    Description: message error 400
  ApiGatewayResponseMessage401:
    Type: String
    Description: message error 401
  ApiGatewayResponseMessage403:
    Type: String
    Description: message error 403
  ApiGatewayResponseMessage404:
    Type: String
    Description: message error 404
  ApiGatewayResponseMessage405:
    Type: String
    Description: message error 405
  ApiGatewayResponseMessage409:
    Type: String
    Description: message error 409
  ApiGatewayResponseMessage429:
    Type: String
    Description: message error 429
  ApiGatewayResponseMessage500:
    Type: String
    Description: message error 500
  SecretArn:
    Type: String
    Description: "arn del secreto que contiene los datos de conexion."
  SecurityGroupIds:
    Type: String
    Description: "Id de la VPC Endpoint que será asociada al API, esta solo se aplica si el API es de tipo privado."
  SubnetIds:
    Type: CommaDelimitedList
    Description: "Identificador de las subnets donde se desplegará el API de desarrollo (Deben estar entre comillas dobles y separadas por comas)."
  DbTarget:
    Type: String
    Description: "Instancia a la que se conectara el lambda master o replica"
  AwsAccountIdToDeploy:
    Type: String
    Description: Identificador de la cuentas AWS donde se desplegará el API de desarrollo.
  RegionToDeploy:
    Type: String
    AllowedValues: [us-east-2, us-west-2, us-east-1]
    ConstraintDescription: must specify us-east-2,us-west-2, us-east-1.
    Description: Región en la cual se realizará el despliegue del ambiente de desarrollo.
  LogLevel:
    Type: String
    AllowedValues: [INFO, DEBUG, WARNING, TRACE]
    ConstraintDescription: must specify INFO, DEBUG, WARNING or TRACE.
    Description: "Nivel de escritura de logs en los lambda INFO,DEBUG,WARNING,TRACE"
  LambdaAuthorizer:
    Type: String
    Description: "Nombre de la función lambda de tipo autorizador para el ambiente de desarrollo."
  DBConnectionExpirationTime:
    Type: Number
    Description: "Tiempo de reconexión a la base de datos."
  UserPoolId:
    Type: String
    Description: "Indica el user poolid para los token de autenticación."
  DaysRetention:
    Type: Number
    Description: "Indica el user poolid para los token de autenticación."
  StageName:
    Type: String
    Description: "Indica el nombre del stage del API Gateway."
  StageMainVersionName:
    Description: Nombre de la version principal de el stage del APIGateway
    Type: String
  # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
  ChannelsCommonsRoleArn:
    Type: String
    Description: Arn del role Channels Commons.
  ChannelsCommonsLayer:
    Type: String
    Description: Arn del layer Channels Commons.
  ExtTimeDeposits:
    Type: String
    Description: "Endpoint al Executor de Time Deposits."
  ExtTimeDepositsApiKey:
    Type: String
    Description: "Api Key del Api Generico Time Deposits."
    Default: "noused"
  ExtDemandDeposits:
    Type: String
    Description: "Endpoint al Executor de Demand Deposits."
  ExtDemandDepositsApiKey:
    Type: String
    Description: "Api Key del Api Generico Demand Deposits."
    Default: "noused"
  ExtLoans:
    Type: String
    Description: "Endpoint al Executor de Loans."
  ExtLoansApiKey:
    Type: String
    Description: "api key del api generico de Loans."
  ExtFinancial:
    Type: String
    Description: "Endpoint al Executor de Financial."
    Default: "url"
  ExtFinancialApiKey:
    Type: String
    Description: "api key del api generico de Financial."
    Default: "noused"
  MainDomain:
    Type: String
    Description: "Dominios propios del Modulo."
  ChannelsCommonsExecutorLambdaConfiguration:
    Description: "ChannelsCommonsExecutorLambda"
    Type: String
    Default: "1024:0:0:0:0:0:INFO"
  Organization:
    Type: String
    Description: "Identificador del dueño componente."
  Package:
    Type: String
    Description: "Identificador del paquete de productos comerciales al que se asocia el componente."
  Version:
    Type: String
    Default: "0.1"
    Description: "Versión del módulo o aplicación a la que pertenece el componente."
  EnvironmentId:
    Type: String
    Description: "Identificador del ambiente."
  EnvironmentIdBaseFront:
    Type: String
    Description: "Identificador del ambiente."
  EnvironmentIdBase:
    Type: String
    Description: "Prefijo de recursos de la infraestructura base para referenciar en el microservicio.Pueden ser [dev,stg,prod o otro personalizado]"
  EnvironmentType:
    Type: String
    AllowedValues: [PRODUCTION, STAGING, QUALITY, DEVELOPMENT]
    ConstraintDescription: must specify PRODUCTION, STAGING, QUALITY or DEVELOPMENT.
  TenantId:
    Type: String
    Description: "Identificador del tenant."
  Project:
    Type: String
    Description: "Identificador del proyecto por el que se crea el componente."
  Module:
    Type: String
    Description: "Identificador del módulo."
  ProcessingType:
    Type: String
    Description: "Tipo de procesamiento."

Globals:
  Function:
    CodeUri: ../cobis-channels-commons-online/target/cobis-channels-commons-serverless-service.jar
    Runtime: java8.al2
    Architectures:
      - arm64
    Tracing: Active
    VpcConfig:
      SecurityGroupIds: [!Ref SecurityGroupIds]
      SubnetIds: !Ref SubnetIds
    Environment:
      Variables:
        DB_TARGET: !Ref DbTarget
        ENVIRONMENT_ID: !Ref EnvironmentId
        EXT_MODULE_URL_TIME_DEPOSITS: !Ref ExtTimeDeposits
        EXT_MODULE_API_KEY_TIME_DEPOSITS: !Ref ExtTimeDepositsApiKey
        EXT_MODULE_URL_DEMAND_DEPOSITS: !Ref ExtDemandDeposits
        EXT_MODULE_API_KEY_DEMAND_DEPOSITS: !Ref ExtDemandDepositsApiKey
        EXT_MODULE_URL_LOANS: !Ref ExtLoans
        EXT_MODULE_API_KEY_LOANS: !Ref ExtLoansApiKey
        EXT_MODULE_URL_FINANCIAL: !Ref ExtFinancial
        EXT_MODULE_API_KEY_FINANCIAL: !Ref ExtFinancialApiKey
        LOG_LEVEL: !Ref LogLevel
        MODULE: !Ref Module
        MAIN_DOMAIN: !Ref MainDomain
        SECRET_ARN: !Ref SecretArn
        TENANT_ID: !Ref TenantId
        DB_CONNECTION_EXPIRATION_TIME: !Ref DBConnectionExpirationTime
        TZ: !Ref TimeZone
    Tags:
      ORGANIZATION: !Ref Organization
      PACKAGE: !Ref Package
      VERSION: !Ref Version
      ENVIRONMENT_TYPE: !Ref EnvironmentType
      ENVIRONMENT_ID: !Ref EnvironmentId
      TENANT_ID: !Ref TenantId
      PROJECT: !Ref Project
      MODULE: !Ref Module
      PROCESSING_TYPE: !Ref ProcessingType

Conditions:
  StageVersionAliasProd: !Equals [!Ref EnvironmentType, PRODUCTION]
  ChannelsCommonsExecutorProvisioned: !Not [ !Equals [ !Select [ 4, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ], 0 ] ]
  ChannelsCommonsExecutorActivateAutoscaling: !And
    - !Not [ !Equals [ !Select [ 2, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ], !Select [ 3, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ] ] ]
    - !Condition ChannelsCommonsExecutorProvisioned

Resources:
  ChannelsCommonsExecutor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Join
        - ""
        - - !Ref EnvironmentIdBaseFront
          - "-ChannelsCommonsExecutor"
      Handler: com.cobis.cloud.channelscommons.aws.lambda.executor.ChannelsCommonsExecutorLambda::handleRequest
      Role: !Sub "${ChannelsCommonsRoleArn}"
      Timeout: 19
      MemorySize: !Select [ 0, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ]
      AutoPublishAlias: !Ref LambdaAliasBeta
      #ReservedConcurrentExecutions: !Select [ 1, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ]
      Layers:
        - !Ref "ChannelsCommonsLayer"
      Environment:
        Variables:
          TOKEN_VALIDATION_KEY_SET_URL: !Sub "https://cognito-idp.${RegionToDeploy}.amazonaws.com/${UserPoolId}/.well-known/jwks.json"
          LOG_LEVEL: !Select [6, !Split [":", !Ref ChannelsCommonsExecutorLambdaConfiguration]]
      Tags:
        ORGANIZATION: !Ref Organization
        PACKAGE: !Ref Package
        VERSION: !Ref Version
        ENVIRONMENT_TYPE: !Ref EnvironmentType
        ENVIRONMENT_ID: !Ref EnvironmentId
        TENANT_ID: !Ref TenantId
        PROJECT: !Ref Project
        MODULE: !Ref Module
        PROCESSING_TYPE: !Ref ProcessingType
      
  ChannelsCommonsExecutorAliasProduction:
    Type: AWS::Lambda::Alias
    DependsOn: "ChannelsCommonsExecutor"
    Properties:
      Description: "Alias a lambda productiva"
      FunctionName: !Ref ChannelsCommonsExecutor
      FunctionVersion: !Select [ 7, !Split [ ":", !Ref ChannelsCommonsExecutor.Version ] ]
      Name: !Ref LambdaAliasProduction
      ProvisionedConcurrencyConfig:
        !If
          - ChannelsCommonsExecutorProvisioned
          - ProvisionedConcurrentExecutions: !Select [ 4, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ]
          - !Ref "AWS::NoValue"

  ChannelsCommonsExecutorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ChannelsCommonsExecutor}
      RetentionInDays: !Ref DaysRetention
      Tags:
        - Key: "ORGANIZATION"
          Value: !Ref Organization
        - Key: "PACKAGE"
          Value: !Ref Package
        - Key: "VERSION"
          Value: !Ref Version
        - Key: "ENVIRONMENT_TYPE"
          Value: !Ref EnvironmentType
        - Key: "ENVIRONMENT_ID"
          Value: !Ref EnvironmentId
        - Key: "TENANT_ID"
          Value: !Ref TenantId
        - Key: "PROJECT"
          Value: !Ref Project
        - Key: "MODULE"
          Value: !Ref Module
        - Key: "PROCESSING_TYPE"
          Value: !Ref ProcessingType

  ChannelsCommonsExecutorScalableTarget:
    Condition: ChannelsCommonsExecutorActivateAutoscaling
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: "ChannelsCommonsExecutorAliasProduction"
    Properties:
      MaxCapacity: !Select [ 2, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ]
      MinCapacity: !Select [ 3, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ]
      ResourceId: !Join
        - ""
        - - "function:"
          - !Ref ChannelsCommonsExecutor
          - ":"
          - !Ref LambdaAliasProduction
      RoleARN: !Sub "${ChannelsCommonsAutoScalingRole}"
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda

  ChannelsCommonsExecutorScalingPolicy:
    Condition: ChannelsCommonsExecutorActivateAutoscaling
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join
        - ""
        - - !Ref EnvironmentId
          - "-ChannelsCommonsExecutor"
          - "AutoScalingPolicy"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ChannelsCommonsExecutorScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization
        TargetValue: !Select [ 5, !Split [ ":", !Ref ChannelsCommonsExecutorLambdaConfiguration ] ]
